export const RESTAURANTS = [
  {
    name: 'Paradise Biryani',
    slug: 'paradise-biryani',
    description: 'Authentic Hyderabadi Dum Biryani.',
    phone: '9000000001',
    email: 'paradise@patheyaexpress.com',
  },
  {
    name: 'Shah Ghouse',
    slug: 'shah-ghouse',
    description: 'Famous for Hyderabadi cuisine.',
    phone: '9000000002',
    email: 'shahghouse@patheyaexpress.com',
  },
  {
    name: 'Mehfil',
    slug: 'mehfil',
    description: 'Multi-cuisine family restaurant.',
    phone: '9000000003',
    email: 'mehfil@patheyaexpress.com',
  },
  {
    name: 'Kritunga',
    slug: 'kritunga',
    description: 'Traditional Andhra cuisine.',
    phone: '9000000004',
    email: 'kritunga@patheyaexpress.com',
  },
  {
    name: 'Pista House',
    slug: 'pista-house',
    description: 'Biryani, Haleem & Bakery.',
    phone: '9000000005',
    email: 'pista@patheyaexpress.com',
  },
  {
    name: 'Bawarchi',
    slug: 'bawarchi',
    description: 'Legendary Hyderabadi restaurant.',
    phone: '9000000006',
    email: 'bawarchi@patheyaexpress.com',
  },
  {
    name: 'Chutneys',
    slug: 'chutneys',
    description: 'South Indian specialties.',
    phone: '9000000007',
    email: 'chutneys@patheyaexpress.com',
  },
  {
    name: 'Barbeque Nation',
    slug: 'barbeque-nation',
    description: 'Live grill experience.',
    phone: '9000000008',
    email: 'bbq@patheyaexpress.com',
  },
  {
    name: 'Dominos Pizza',
    slug: 'dominos-pizza',
    description: 'Pizza delivery.',
    phone: '9000000009',
    email: 'dominos@patheyaexpress.com',
  },
  {
    name: 'Pizza Hut',
    slug: 'pizza-hut',
    description: 'Pizzas & pasta.',
    phone: '9000000010',
    email: 'pizzahut@patheyaexpress.com',
  },
  {
    name: 'KFC',
    slug: 'kfc',
    description: 'Fried chicken.',
    phone: '9000000011',
    email: 'kfc@patheyaexpress.com',
  },
  {
    name: "McDonald's",
    slug: 'mcdonalds',
    description: 'Burgers & fries.',
    phone: '9000000012',
    email: 'mcd@patheyaexpress.com',
  },
  {
    name: 'Burger King',
    slug: 'burger-king',
    description: 'Flame grilled burgers.',
    phone: '9000000013',
    email: 'bk@patheyaexpress.com',
  },
  {
    name: 'Subway',
    slug: 'subway',
    description: 'Fresh sandwiches.',
    phone: '9000000014',
    email: 'subway@patheyaexpress.com',
  },
  {
    name: 'Behrouz Biryani',
    slug: 'behrouz-biryani',
    description: 'Royal biryani.',
    phone: '9000000015',
    email: 'behrouz@patheyaexpress.com',
  },
  {
    name: 'Imperial Restaurant',
    slug: 'imperial',
    description: 'Hyderabad favorite.',
    phone: '9000000016',
    email: 'imperial@patheyaexpress.com',
  },
  {
    name: 'Cafe Niloufer',
    slug: 'cafe-niloufer',
    description: 'Tea & bakery.',
    phone: '9000000017',
    email: 'niloufer@patheyaexpress.com',
  },
  {
    name: 'Karachi Bakery',
    slug: 'karachi-bakery',
    description: 'Bakery & biscuits.',
    phone: '9000000018',
    email: 'karachi@patheyaexpress.com',
  },
  {
    name: 'Hotel Shadab',
    slug: 'hotel-shadab',
    description: 'Traditional Mughlai cuisine.',
    phone: '9000000019',
    email: 'shadab@patheyaexpress.com',
  },
  {
    name: 'Absolute Barbecue',
    slug: 'absolute-barbecue',
    description: 'Premium buffet.',
    phone: '9000000020',
    email: 'absolutebbq@patheyaexpress.com',
  },
];
